hosts: all
sudo: yes

  tasks:
    - name: Pull docker image
      shell: docker pull priyanka301/springpetclinic

    - name: Stop docker container
      shell: docker rm -f petclinic

    - name: Run docker container
      shell: docker run -itd -p 9000:8080 --name petclinic priyanka301/springpetclinic
